name: Postman Newman Tests

on:
  push:
  workflow_dispatch:

jobs:
  postman-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js 24
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Install Newman and reporter
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra
      - name: Run Postman collection
        run: |
          newman run test/collection.json \
            -e test
            /env.json \
            --env-var "secret_key=${{ secrets.NASA_API_KEY }}" \
            -r cli,htmlextra \
            --reporter-htmlextra-export test-report.html \
            --reporter-htmlextra-title "Postman Test Report" \
            --reporter-htmlextra-logs
      - name: Upload Newman HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: postman-test-report
          path: test-report.html

      - name: Upload Newman log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: postman-newman-log
          path: newman/*.json
